#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults
PROCESS_NAME="soulseek"

check_container_initialized
check_service_initialized init
check_service_initialized 40-novnc
liftoff

export HOME="/data"
export DISPLAY=":1"
print_start "Starting Soulseek"
silent /app/SoulseekQt

liftoff